### ISSUE TITLE
Direct link to wradlib docu

### ISSUE THREAD

**Issue by heistermann** [wradlib/landing-page#6]
I'd prefer if the "Documentration" menu item directly linked to http://wradlib.github.io/wradlib-docs. If you'd agree, could that be facilitated by

```
MENUITEMS = (
    ('Home', '/'),
    ('Documentation', '/wradlib-docs/'),
    ('Community', '/community/'),
    ('About', '/about/'),
)
```

in `pelicanconf.py`?

**Comment by kmuehlbauer** [comment]
Sure, go ahead.
